title: Copy for Scrapbox
description: |
  Copy for Scrapbox is a Chrome extension which helps you copy tab(s) as Scrapbox notation easily.

author:
  name: Tatsuya Sato
  email: satoryu.1981@gmail.com

lsi: false
safe: true
source: ./
baseurl: /copy-for-scrapbox
incremental: false
highlighter: rouge

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: minima

google_analytics: G-DM9EN1G7ZE

repository: satoryu/copy-for-scrapbox