on:
  pull_requests:
    branches:
      - main

jobs:
  test:
    - uses: actions/checkout@3

    - uses: actions/setup-node
      with:
        node-version: 18
        cache: 'npm'

    - run: npm install
    - run: npm test
