on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3

      - uses: actions/setup-node
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install
      - run: npm test
