on: [push]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Packaging
        run: |
          mkdir packages
          zip -r packages/copy-for-scrapbox.zip ./ \
            -x '*.git*' \
            -x '*.md' \
            -x 'LICENSE' \
            -x '*packages/*'
