on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  build:
    name: Build a package
    needs: test

    runs-on: ubuntu-latest

    environment: release

    steps:
      - uses: actions/checkout@v3

      - name: Extract version from manifest.json
        id: manifest_version
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq -r .version package.json

      - name: Define package name
        id: package_name
        run: echo 'package_name=copy-for-scrapbox-${{steps.manifest_version.outputs.value}}-chrome' >> $GITHUB_OUTPUT

      - run: npm install
      - name: Packaging
        run: npm run zip

      - uses: actions/upload-artifact@v4
        with:
          name: ${{steps.package_name.outputs.package_name}}.zip
          path: .output/${{steps.package_name.outputs.package_name}}.zip

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') # Run only when tagged like v1.0.1
        with:
          files: .output/${{steps.package_name.outputs.package_name}}.zip
          generate_release_notes: true
