on: [push]
# TODO: this trigger MUST be replaced with the following one:
# on:
#   push:
#     tags: 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Packaging
        run: |
          mkdir packages
          zip -r packages/copy-for-scrapbox.zip ./ \
            -x '*.git*' \
            -x '*.md' \
            -x 'LICENSE' \
            -x '*packages/*'
      - uses: actions/upload-artifact@v2
        with:
          name: copy-for-scrapbox.zip
          path: packages/copy-for-scrapbox.zip
